### ISSUE TITLE
Make it Compatible With GeyserMC

### ISSUE THREAD

**Issue by BobtheBob123456** [Phoenix616/ResourcepacksPlugins#71] opened 2022-08-27 05:05 UTC
Basically how it soueach.

 Make it so that bedrock players are exempt from the resource packs if they are forced, and/or making it possible for bedrock players to be sent their own resource packs for each world.

**Comment by BobtheBob123456** [comment] 2022-08-27 05:07
Never mind. I see this has already been discussed.

**Comment by Phoenix616** [comment] 2022-10-03 19:09
Duplicate of #58

**Closed by Phoenix616** 2022-10-03 19:09 UTC
